# Generated by Django 5.2 on 2025-05-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentsession_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
