# Generated by Django 5.2 on 2025-05-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentprofile_email_studentprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='community',
            field=models.BooleanField(default=False),
        ),
    ]
