# Generated by Django 5.2 on 2025-05-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentprofile_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='current_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='question_order',
            field=models.JSONField(default=list),
        ),
    ]
