# Generated by Django 5.2 on 2025-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentsession_current_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
