# Generated by Django 5.2 on 2025-05-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option_id',
            field=models.CharField(default='option_a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='test_desc',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
