# Generated by Django 5.2 on 2025-05-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testportal', '0002_remove_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
