# Generated by Django 5.2 on 2025-05-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testportal', '0004_remove_testquestion_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
