# Generated by Django 5.2 on 2025-05-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
