# Generated by Django 5.2 on 2025-05-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements_manager', '0002_alter_announcements_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
