# Generated by Django 5.2 on 2025-04-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('enrollment_number', models.CharField(blank=True, max_length=20)),
                ('year_of_study', models.CharField(blank=True, max_length=10)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college_id', models.ImageField(blank=True, null=True, upload_to='college_ids/')),
            ],
        ),
    ]
