# Generated by Django 5.2 on 2025-04-26 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_verified_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college',
        ),
        migrations.RemoveField(
            model_name='user',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enrollment_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year_of_study',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('enrollment_number', models.CharField(blank=True, max_length=20)),
                ('year_of_study', models.CharField(blank=True, max_length=10)),
                ('college_id', models.ImageField(blank=True, null=True, upload_to='college_ids/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
