# Generated by Django 5.2 on 2025-04-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
